version: '3.9'

services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chroma-vector-db
    environment:
      - IS_PERSISTENT=TRUE
      - PERSISTENT_DIR=/chroma/data
    volumes:
      - ./chroma_data:/chroma/data
    ports:
      - "8001:8000"
    networks:
      - rag-net

  rag-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-fastapi-service
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CHROMA_MODE=docker
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
    volumes:
      - ../chunks.json:/app/chunks.json
    depends_on:
      - chromadb
    networks:
      - rag-net

networks:
  rag-net:
    driver: bridge
